### ISSUE TITLE
Add a .gitignore file

### ISSUE THREAD

**Issue by swaathi** [pratian-pyclub/nitesh-suresh#5]
Here's a sample `.gitignore` for Python,

```
*.DS_STORE
*.pid
*.pyc
*.log
dump.rdb
venv
helloworld.egg-info
build
dist
cache
```

And then follow the instructions here to clear cache, https://blog.skcript.com/gitignore-not-working-here-s-the-solution-c16e7b34dc9f#.ti5ezpky0.

**Comment by Niteshsuresh** [comment]
Added gitignore file. Thank you.

**Comment by swaathi** [comment]
Add `.gitignore` to the root! Not inside. You'll have to modify the filenames within the `.gitignore` accordingly.

**Comment by Niteshsuresh** [comment]
.gitignore now moved at root folder.
